### ISSUE TITLE
docker-compose.yml error

### ISSUE THREAD

**Issue by Franconian-IT** [MathiasRenner/invoiceninja-docker#8]
The last commit [f46fd17](https://github.com/MathiasRenner/invoiceninja-docker/commit/f46fd17248a6c69b2770ff85b35b99a21b5c65e8) to the docker-compose.yml causes an error, when I try to start the container. Currently the easy setup script and manual start with docker-compose is broken, because of this error:

```
user@ubuntu:~/invoiceninja$ docker-compose up -d

ERROR: yaml.scanner.ScannerError: while scanning a simple key
  in "./docker-compose.yml", line 25, column 7
could not found expected ':'
  in "./docker-compose.yml", line 26, column 7
```
The error is caused by code line 25 in docker-compose.yml:
`APP_CIPHER=AES-256-CBC`

I think that the equals sign is problematic.
When I change the line to:
`APP_CIPHER: AES-256-CBC`
It works again, but I do not know if App_CIPHER still serves its purpose, after this change.

**Comment by MathiasRenner** [comment]
@Franconian-IT : Thank you very much for this hint. This is an error of course, the fix you suggest works. I just fixed it (see commit above this message).
